project_id = "xfwovoctvaaihxasmtsf"

[functions.scrape-events]
verify_jwt = false

[functions.send-push]
verify_jwt = false

[functions.verify-events]
verify_jwt = false

[functions.create-donation]
verify_jwt = false